# config/secrets.yml
production:
  secret_key_base: d1eeb23773b0ecafcfb2b139c05277fae71f2608a44570a914430c6a2af824c388cb316d3155e82301e1b7af48dda286e911fc21459fa473879b638f717da210
  aws_secret: abcde
  some_password: abcdex

development:
  secret_key_base: static_secret_key
  aws_secret: abcde

test:
  secret_key_base: static_test_secret_key


#not_indented: key for all env in once
secret_key_base: global_key_for_all_env